// UI Issue interface (different from database Issue)
export interface Issue {
  id: string;
  title: string;
  repository: string;
  description: string;
  language: string;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  stars: number;
  timeEstimate: string;
  labels: string[];
  author: string;
  createdAt: string;
  url: string;
  isSaved?: boolean;
}

export const groupOptions = [
    { id: 'education', value: 'education', label: 'Education', icon: '🎓' },
    { id: 'finance', value: 'finance', label: 'Finance', icon: '💰' },
    { id: 'healthcare', value: 'healthcare', label: 'Healthcare', icon: '🏥' },
    { id: 'ecommerce', value: 'ecommerce', label: 'E-commerce', icon: '🛒' },
    { id: 'social_media', value: 'social_media', label: 'Social Media', icon: '📱' },
    { id: 'gaming', value: 'gaming', label: 'Gaming', icon: '🎮' },
    { id: 'productivity', value: 'productivity', label: 'Productivity', icon: '⏱️' },
    { id: 'travel', value: 'travel', label: 'Travel', icon: '✈️' },
    { id: 'food_delivery', value: 'food_delivery', label: 'Food Delivery', icon: '🍔' },
    { id: 'real_estate', value: 'real_estate', label: 'Real Estate', icon: '🏠' },
    { id: 'fitness', value: 'fitness', label: 'Fitness', icon: '💪' },
    { id: 'entertainment', value: 'entertainment', label: 'Entertainment', icon: '🎭' },
    { id: 'news_media', value: 'news_media', label: 'News & Media', icon: '📰' },
    { id: 'transportation', value: 'transportation', label: 'Transportation', icon: '🚗' },
    { id: 'environment', value: 'environment', label: 'Environment', icon: '🌿' },
    { id: 'iot', value: 'iot', label: 'IoT', icon: '🔌' },
    { id: 'cybersecurity', value: 'cybersecurity', label: 'Cybersecurity', icon: '🔒' },
    { id: 'ar_vr', value: 'ar_vr', label: 'AR/VR', icon: '🥽' },
    { id: 'music', value: 'music', label: 'Music', icon: '🎵' },
    { id: 'nonprofit', value: 'nonprofit', label: 'Non-profit', icon: '🤝' },
    { id: 'marketing', value: 'marketing', label: 'Marketing', icon: '📣' },
    { id: 'ai', value: 'ai', label: 'AI', icon: '🤖' },
    { id: 'dev_tools', value: 'dev_tools', label: 'Dev Tools', icon: '🛠️' }
  ]
  
  export const contributionOptions = [
    { id: 'docs', value: 'docs', label: 'Documentation', icon: '📚' },
    { id: 'features', value: 'features', label: 'Features', icon: '✨' },
    { id: 'ui_design', value: 'ui_design', label: 'UI Design', icon: '🎨' },
    { id: 'optimization', value: 'optimization', label: 'Optimization', icon: '⚡' },
    { id: 'testing', value: 'testing', label: 'Testing', icon: '🧪' },
    { id: 'localization', value: 'localization', label: 'Localization', icon: '🌐' },
    { id: 'reviews', value: 'reviews', label: 'Code Reviews', icon: '👀' },
    { id: 'bugs', value: 'bugs', label: 'Bug Finding', icon: '🐛' },
    { id: 'automation', value: 'automation', label: 'Automation CI/CD', icon: '🤖' },
    { id: 'community', value: 'community', label: 'Community Management', icon: '👥' }
  ]

export const languagesOptions = [
    { id: 'javascript', value: 'javascript', label: 'JavaScript', icon: '🟨' },
    { id: 'python', value: 'python', label: 'Python', icon: '🐍' },
    { id: 'java', value: 'java', label: 'Java', icon: '☕' },
    { id: 'typescript', value: 'typescript', label: 'TypeScript', icon: '🔷' },
    { id: 'csharp', value: 'csharp', label: 'C#', icon: '♯' },
    { id: 'php', value: 'php', label: 'PHP', icon: '🐘' },
    { id: 'c_plus_plus', value: 'c_plus_plus', label: 'C++', icon: '➕' },
    { id: 'ruby', value: 'ruby', label: 'Ruby', icon: '💎' },
    { id: 'c', value: 'c', label: 'C', icon: '🔵' },
    { id: 'go', value: 'go', label: 'Go', icon: '🐹' },
    { id: 'swift', value: 'swift', label: 'Swift', icon: '🦅' },
    { id: 'kotlin', value: 'kotlin', label: 'Kotlin', icon: '🤖' },
    { id: 'rust', value: 'rust', label: 'Rust', icon: '🦀' },
    { id: 'dart', value: 'dart', label: 'Dart', icon: '🎯' },
    { id: 'scala', value: 'scala', label: 'Scala', icon: '🔺' },
    { id: 'shell', value: 'shell', label: 'Shell', icon: '🐚' },
    { id: 'objective_c', value: 'objective_c', label: 'Objective-C', icon: '🍏' },
    { id: 'r', value: 'r', label: 'R', icon: '📊' },
    { id: 'perl', value: 'perl', label: 'Perl', icon: '🐪' },
    { id: 'haskell', value: 'haskell', label: 'Haskell', icon: 'λ' },
    { id: 'elixir', value: 'elixir', label: 'Elixir', icon: '💧' },
    { id: 'clojure', value: 'clojure', label: 'Clojure', icon: '🌿' },
    { id: 'lua', value: 'lua', label: 'Lua', icon: '🌙' },
    { id: 'matlab', value: 'matlab', label: 'MATLAB', icon: '📐' },
    { id: 'groovy', value: 'groovy', label: 'Groovy', icon: '🎵' }
];


export const mockIssues: Issue[] = [
  {
    id: "1",
    title: "Add dark mode support to documentation site",
    repository: "freeCodeCamp/freeCodeCamp",
    description: "We need to implement dark mode for better accessibility. This is a great first contribution! The toggle should persist user preference across sessions.",
    language: "JavaScript",
    difficulty: "Beginner",
    stars: 388000,
    timeEstimate: "2-4 hours",
    labels: ["good first issue", "documentation", "frontend", "accessibility"],
    author: "freeCodeCamp",
    createdAt: "2 days ago",
    url: "https://github.com/freeCodeCamp/freeCodeCamp/issues"
  },
  {
    id: "2",
    title: "Improve error messages for new contributors",
    repository: "microsoft/vscode",
    description: "Make error messages more beginner-friendly. This will help new developers understand what went wrong and how to fix it.",
    language: "TypeScript",
    difficulty: "Beginner",
    stars: 155000,
    timeEstimate: "1-3 hours",
    labels: ["good first issue", "documentation", "ux"],
    author: "microsoft",
    createdAt: "1 day ago",
    url: "https://github.com/microsoft/vscode/issues"
  },
  {
    id: "3",
    title: "Add unit tests for authentication module",
    repository: "nodejs/node",
    description: "We need comprehensive unit tests for the new authentication features. Great opportunity to learn testing best practices!",
    language: "JavaScript",
    difficulty: "Intermediate",
    stars: 101000,
    timeEstimate: "8-12 hours",
    labels: ["enhancement", "testing", "authentication"],
    author: "nodejs",
    createdAt: "3 days ago",
    url: "https://github.com/nodejs/node/issues"
  },
  {
    id: "4",
    title: "Create getting started guide for beginners",
    repository: "facebook/react",
    description: "Help us write a beginner-friendly guide for new React developers. If you've recently learned React, this is perfect for you!",
    language: "JavaScript",
    difficulty: "Beginner",
    stars: 220000,
    timeEstimate: "4-6 hours",
    labels: ["good first issue", "documentation", "beginner-friendly"],
    author: "facebook",
    createdAt: "5 days ago",
    url: "https://github.com/facebook/react/issues"
  },
  {
    id: "5",
    title: "Fix responsive layout on mobile devices",
    repository: "vercel/next.js",
    description: "The sidebar component doesn't display correctly on mobile screens. Need to adjust CSS media queries and test on various devices.",
    language: "TypeScript",
    difficulty: "Beginner",
    stars: 118000,
    timeEstimate: "2-4 hours",
    labels: ["bug", "css", "mobile", "good first issue"],
    author: "vercel",
    createdAt: "4 days ago",
    url: "https://github.com/vercel/next.js/issues"
  },
  {
    id: "6",
    title: "Add Python type hints to utility functions",
    repository: "pallets/flask",
    description: "Add type hints to improve code quality and developer experience. Great way to learn Python typing!",
    language: "Python",
    difficulty: "Beginner",
    stars: 65000,
    timeEstimate: "3-5 hours",
    labels: ["good first issue", "enhancement", "typing"],
    author: "pallets",
    createdAt: "1 week ago",
    url: "https://github.com/pallets/flask/issues"
  },
  {
    id: "7",
    title: "Improve CLI help documentation",
    repository: "django/django",
    description: "Make command-line interface help text more descriptive and user-friendly. Perfect for documentation enthusiasts!",
    language: "Python",
    difficulty: "Beginner",
    stars: 75000,
    timeEstimate: "2-3 hours",
    labels: ["good first issue", "documentation", "cli"],
    author: "django",
    createdAt: "3 days ago",
    url: "https://github.com/django/django/issues"
  },
  {
    id: "8",
    title: "Add accessibility labels to UI components",
    repository: "flutter/flutter",
    description: "Improve accessibility by adding proper ARIA labels and semantic HTML. Help make apps accessible to everyone!",
    language: "Dart",
    difficulty: "Intermediate",
    stars: 160000,
    timeEstimate: "6-8 hours",
    labels: ["accessibility", "enhancement", "a11y"],
    author: "flutter",
    createdAt: "6 days ago",
    url: "https://github.com/flutter/flutter/issues"
  },
  {
    id: "9",
    title: "Create example projects for documentation",
    repository: "rust-lang/rust",
    description: "We need more practical examples in our documentation. If you're learning Rust, contributing examples is a great way to solidify your knowledge!",
    language: "Rust",
    difficulty: "Beginner",
    stars: 91000,
    timeEstimate: "4-8 hours",
    labels: ["good first issue", "documentation", "examples"],
    author: "rust-lang",
    createdAt: "2 days ago",
    url: "https://github.com/rust-lang/rust/issues"
  },
  {
    id: "10",
    title: "Add validation to form inputs",
    repository: "vuejs/vue",
    description: "Implement client-side validation for form components. Great opportunity to learn Vue.js validation patterns!",
    language: "JavaScript",
    difficulty: "Intermediate",
    stars: 205000,
    timeEstimate: "5-7 hours",
    labels: ["enhancement", "forms", "validation"],
    author: "vuejs",
    createdAt: "1 week ago",
    url: "https://github.com/vuejs/vue/issues"
  },
  {
    id: "11",
    title: "Add issue templates to repository",
    repository: "firstcontributions/first-contributions",
    description: "Add or improve GitHub issue templates for new contributors.",
    language: "Markdown",
    difficulty: "Beginner",
    stars: 39000,
    timeEstimate: "1-2 hours",
    labels: ["good first issue", "documentation"],
    author: "firstcontributions",
    createdAt: "3 months ago",
    url: "https://github.com/firstcontributions/first-contributions/issues"
  },
  {
    id: "12",
    title: "Update README badges",
    repository: "public-apis/public-apis",
    description: "Refresh or add status badges (build, license) in README.",
    language: "Markdown",
    difficulty: "Beginner",
    stars: 240000,
    timeEstimate: "1 hour",
    labels: ["good first issue", "docs"],
    author: "public-apis",
    createdAt: "2 days ago",
    url: "https://github.com/public-apis/public-apis/issues"
  },
  {
    id: "13",
    title: "Improve example snippet in documentation",
    repository: "30-seconds/30-seconds-of-code",
    description: "Fix or enhance code snippet examples in documentation pages.",
    language: "JavaScript",
    difficulty: "Beginner",
    stars: 80000,
    timeEstimate: "1-3 hours",
    labels: ["good first issue", "documentation", "frontend"],
    author: "30-seconds",
    createdAt: "5 days ago",
    url: "https://github.com/30-seconds/30-seconds-of-code/issues"
  },
  {
    id: "14",
    title: "Add project to awesome-for-beginners list",
    repository: "MunGell/awesome-for-beginners",
    description: "Submit a pull request adding a beginner-friendly project link to the list.",
    language: "Markdown",
    difficulty: "Beginner",
    stars: 30000,
    timeEstimate: "1 hour",
    labels: ["good first issue", "list", "meta"],
    author: "MunGell",
    createdAt: "1 week ago",
    url: "https://github.com/MunGell/awesome-for-beginners/issues"
  },
  {
    id: "15",
    title: "Fix broken documentation link",
    repository: "freeCodeCamp/freeCodeCamp",
    description: "Update or correct a broken link in the project's documentation.",
    language: "HTML",
    difficulty: "Beginner",
    stars: 350000,
    timeEstimate: "30 minutes",
    labels: ["good first issue", "documentation"],
    author: "freeCodeCamp",
    createdAt: "1 day ago",
    url: "https://github.com/freeCodeCamp/freeCodeCamp/issues"
  },
  {
    id: "16",
    title: "Add accessibility improvements to landing page",
    repository: "vercel/next.js",
    description: "Enhance accessibility by improving ARIA labels and semantic elements on the Next.js homepage.",
    language: "TypeScript",
    difficulty: "Beginner",
    stars: 125000,
    timeEstimate: "2-4 hours",
    labels: ["good first issue", "a11y", "frontend"],
    author: "vercel",
    createdAt: "3 days ago",
    url: "https://github.com/vercel/next.js/issues/67890"
  },
  {
    id: "17",
    title: "Improve error messages in CLI output",
    repository: "cli/cli",
    description: "Refactor error messages for clarity and consistency in GitHub CLI.",
    language: "Go",
    difficulty: "Beginner",
    stars: 42000,
    timeEstimate: "1-3 hours",
    labels: ["good first issue", "cli", "ux"],
    author: "github",
    createdAt: "1 week ago",
    url: "https://github.com/cli/cli/issues/7890"
  },
  {
    id: "18",
    title: "Fix theme toggle animation in docs",
    repository: "chakra-ui/chakra-ui",
    description: "Smoothen the theme toggle transition animation on documentation site.",
    language: "TypeScript",
    difficulty: "Beginner",
    stars: 36000,
    timeEstimate: "2 hours",
    labels: ["good first issue", "frontend", "animation"],
    author: "chakra-ui",
    createdAt: "4 days ago",
    url: "https://github.com/chakra-ui/chakra-ui/issues/2456"
  },
  {
    id: "19",
    title: "Add dark mode to blog",
    repository: "gatsbyjs/gatsby",
    description: "Add dark mode toggle feature for the Gatsby official blog.",
    language: "JavaScript",
    difficulty: "Beginner",
    stars: 56000,
    timeEstimate: "2 hours",
    labels: ["good first issue", "frontend", "docs"],
    author: "gatsbyjs",
    createdAt: "2 weeks ago",
    url: "https://github.com/gatsbyjs/gatsby/issues/33444"
  },
  {
    id: "20",
    title: "Add missing tests for helper functions",
    repository: "axios/axios",
    description: "Add unit tests for helper functions in axios utils folder.",
    language: "JavaScript",
    difficulty: "Beginner",
    stars: 105000,
    timeEstimate: "2-3 hours",
    labels: ["good first issue", "test", "backend"],
    author: "axios",
    createdAt: "1 week ago",
    url: "https://github.com/axios/axios/issues/5100"
  },
  {
    id: "21",
    title: "Translate README to Spanish",
    repository: "open-metadata/OpenMetadata",
    description: "Add Spanish translation for the README file to improve community reach.",
    language: "Markdown",
    difficulty: "Beginner",
    stars: 8000,
    timeEstimate: "2-4 hours",
    labels: ["good first issue", "translation", "docs"],
    author: "open-metadata",
    createdAt: "5 days ago",
    url: "https://github.com/open-metadata/OpenMetadata/issues/876"
  },
  {
    id: "22",
    title: "Add contribution guidelines",
    repository: "EddieHubCommunity/LinkFree",
    description: "Create CONTRIBUTING.md file to help new developers start contributing easily.",
    language: "Markdown",
    difficulty: "Beginner",
    stars: 2500,
    timeEstimate: "1 hour",
    labels: ["good first issue", "docs"],
    author: "EddieHubCommunity",
    createdAt: "2 weeks ago",
    url: "https://github.com/EddieHubCommunity/LinkFree/issues/102"
  },
  {
    id: "23",
    title: "Improve homepage layout responsiveness",
    repository: "open-sauced/open-sauced",
    description: "Fix layout alignment issues for smaller viewports on homepage.",
    language: "React",
    difficulty: "Beginner",
    stars: 900,
    timeEstimate: "1-3 hours",
    labels: ["good first issue", "frontend", "responsive"],
    author: "open-sauced",
    createdAt: "3 days ago",
    url: "https://github.com/open-sauced/open-sauced/issues/654"
  },
  {
    id: "24",
    title: "Enhance login error UI",
    repository: "appwrite/appwrite",
    description: "Improve the error messages and toast styles during login process.",
    language: "TypeScript",
    difficulty: "Beginner",
    stars: 40000,
    timeEstimate: "1 hour",
    labels: ["good first issue", "frontend", "ux"],
    author: "appwrite",
    createdAt: "6 days ago",
    url: "https://github.com/appwrite/appwrite/issues/2512"
  },
  {
    id: "25",
    title: "Fix typos in docs",
    repository: "supabase/supabase",
    description: "Proofread and fix minor grammatical errors in Supabase documentation.",
    language: "Markdown",
    difficulty: "Beginner",
    stars: 75000,
    timeEstimate: "1 hour",
    labels: ["good first issue", "docs"],
    author: "supabase",
    createdAt: "4 days ago",
    url: "https://github.com/supabase/supabase/issues/3521"
  },
  {
    id: "26",
    title: "Update dependencies in package.json",
    repository: "facebook/react",
    description: "Update outdated dependencies and ensure tests pass successfully.",
    language: "JavaScript",
    difficulty: "Beginner",
    stars: 230000,
    timeEstimate: "2 hours",
    labels: ["good first issue", "maintenance"],
    author: "facebook",
    createdAt: "3 weeks ago",
    url: "https://github.com/facebook/react/issues/27652"
  },
  {
    id: "27",
    title: "Refactor CSS to Tailwind classes",
    repository: "tailwindlabs/tailwindcss",
    description: "Replace manual CSS rules with appropriate Tailwind utility classes.",
    language: "TypeScript",
    difficulty: "Beginner",
    stars: 75000,
    timeEstimate: "2-3 hours",
    labels: ["good first issue", "frontend", "refactor"],
    author: "tailwindlabs",
    createdAt: "2 days ago",
    url: "https://github.com/tailwindlabs/tailwindcss/issues/5220"
  },
  {
    id: "28",
    title: "Add favicon and metadata",
    repository: "mozilla/pdf.js",
    description: "Add favicon and proper meta tags to improve SEO and branding.",
    language: "JavaScript",
    difficulty: "Beginner",
    stars: 49000,
    timeEstimate: "1 hour",
    labels: ["good first issue", "frontend"],
    author: "mozilla",
    createdAt: "1 week ago",
    url: "https://github.com/mozilla/pdf.js/issues/16656"
  },
  {
    id: "29",
    title: "Add dark mode support",
    repository: "mdn/mdn",
    description: "Implement dark mode support for MDN developer documentation pages.",
    language: "HTML",
    difficulty: "Beginner",
    stars: 9000,
    timeEstimate: "3 hours",
    labels: ["good first issue", "frontend", "a11y"],
    author: "mdn",
    createdAt: "2 weeks ago",
    url: "https://github.com/mdn/mdn/issues/455"
  },
  {
    id: "30",
    title: "Create tests for data parser",
    repository: "pandas-dev/pandas",
    description: "Add missing tests for CSV and JSON parsers.",
    language: "Python",
    difficulty: "Beginner",
    stars: 42000,
    timeEstimate: "2-3 hours",
    labels: ["good first issue", "test"],
    author: "pandas-dev",
    createdAt: "5 days ago",
    url: "https://github.com/pandas-dev/pandas/issues/54431"
  },
  {
    id: "31",
    title: "Add Hindi translation to docs",
    repository: "django/django",
    description: "Add missing translations for error messages in Hindi.",
    language: "Python",
    difficulty: "Beginner",
    stars: 80000,
    timeEstimate: "3 hours",
    labels: ["good first issue", "translation"],
    author: "django",
    createdAt: "1 week ago",
    url: "https://github.com/django/django/issues/35432"
  },
  {
    id: "32",
    title: "Fix navbar overlap on small screens",
    repository: "vuejs/core",
    description: "Resolve responsive layout issue with navbar collapsing improperly.",
    language: "TypeScript",
    difficulty: "Beginner",
    stars: 45000,
    timeEstimate: "2 hours",
    labels: ["good first issue", "frontend"],
    author: "vuejs",
    createdAt: "3 days ago",
    url: "https://github.com/vuejs/core/issues/8143"
  },
  {
    id: "33",
    title: "Add contributor guidelines",
    repository: "nodejs/node",
    description: "Add detailed guidelines for first-time contributors to Node.js core.",
    language: "Markdown",
    difficulty: "Beginner",
    stars: 105000,
    timeEstimate: "2 hours",
    labels: ["good first issue", "docs"],
    author: "nodejs",
    createdAt: "1 week ago",
    url: "https://github.com/nodejs/node/issues/51710"
  },
  {
    id: "34",
    title: "Update logo asset to SVG",
    repository: "tensorflow/tensorflow",
    description: "Replace outdated PNG logos with optimized SVG format.",
    language: "Python",
    difficulty: "Beginner",
    stars: 180000,
    timeEstimate: "1 hour",
    labels: ["good first issue", "docs", "assets"],
    author: "tensorflow",
    createdAt: "4 days ago",
    url: "https://github.com/tensorflow/tensorflow/issues/67288"
  },
  {
    id: "35",
    title: "Add missing alt text for images",
    repository: "microsoft/vscode",
    description: "Improve accessibility by adding alt text to all images in documentation.",
    language: "TypeScript",
    difficulty: "Beginner",
    stars: 155000,
    timeEstimate: "2 hours",
    labels: ["good first issue", "a11y", "docs"],
    author: "microsoft",
    createdAt: "2 days ago",
    url: "https://github.com/microsoft/vscode/issues/207560"
  }
];
